### ISSUE TITLE
Review #1 - No se subió bien la pagina a Github Pages

### ISSUE THREAD

**Issue by FacundoEG** [Raneon/Modulo3-WebPage#1]
Hola Matias, sabes que encontre un problema en tu repositorio, fijate que cuando quiero ingresar al link de github pages que tenes en el readme me devuelve esto:

![image](https://user-images.githubusercontent.com/79592789/130548751-42a88804-de25-45bb-b863-ec03981ae772.png)

Estuve revisando tu repositorio y parece que subiste la pagina en tu branch "main", el tema es que en ese branch solo tenes el readme dentro.

![image](https://user-images.githubusercontent.com/79592789/130548853-b94f0922-91b9-4d9d-acc8-d525296b490a.png)

Y todo el contenido del desafío lo tenes dentro del branch "master"

![image](https://user-images.githubusercontent.com/79592789/130548939-76d1fe08-4e3d-4f91-b161-abe63238775b.png)

Te recomendaría que revises si podes levantar la pagina usando el Source "master" en la Github Pages:

![image](https://user-images.githubusercontent.com/79592789/130549077-2ea563fd-9529-4d10-9f87-4bbb36ceaf4e.png)

Acordate que para poder revisar el desafío, tenes que tener la pagina subida correctamente para visualizarla.

Cualquier cosita manda mensaje por aca.

Saludos!

**Comment by Raneon** [comment]
Hola Facu,

Gracias por tomarte el tiempo de revisar y explicarme,

Croe que ahi esta corregido, podes chequiar?

**Comment by FacundoEG** [comment]
Hola Mati! Lo subiste todo a un solo branch pero cuando entro no carga la pagina ! 

![ED46243A-9B64-41A6-8473-7C77F5BBC3E0](https://user-images.githubusercontent.com/79592789/130711220-ec3f7190-093d-465d-bb6f-41b0e2e24350.jpeg)

Fijate de cuando lo cargues en GitHub Pages, de elegir que use el branch master! Trata de revisar que si o si te dejé entrar, cualquier cosa déjame un screenshot de cómo lo tenes configurado a la hora de subirlo y vemos!

**Comment by Raneon** [comment]
Hola Facu,

Gracias de vuelta y sorry por el incoveniente, 

Ahi anda, ya lo probe

Gracias viejo

**Comment by FacundoEG** [comment]
De nada! No me toca hacer la review ahora pero al menos ya sabes que anda! Me quedo más tranquilo.

Te cierro el issue entonces.

Saludos y éxitos con el desafío!
